name: CI
env:
  DOTNET_VERSION: '9.0.101'
on:
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install Fantomas tool
        run: dotnet tool restore
      - name: Run Fantomas and check for changes
        run: dotnet fantomas --check .
  unit-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: unit-test
          run: dotnet test BintLangLib.Tests
  integration-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: unit-test
          run: dotnet test BintLang.IntegrationTests
